{
 "title": "Docker Swarm Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "leader",
    "label": "Leader",
    "query": {
     "query": "query_result(swarm_manager_leader{} == 1)"
    }
   },
   {
    "name": "v_swarm_id",
    "query": {
     "query": "label_values(swarm_node_info{instance=\"$leader\"},swarm_id)"
    }
   },
   {
    "name": "v_nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(swarm_node_info{swarm_id=\"$v_swarm_id\"},instance)"
    }
   },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(swarm_node_info{swarm_id=\"$v_swarm_id\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Docker Engine Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{instance=\"$leader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Swarm Node Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Fault Tolerance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(swarm_manager_nodes{instance=~\"$v_nodes\", state=\"ready\"} > 0)",
     "legendFormat": "__auto"
    },
    { "expression": "($A - 1) / 2", "type": "math" }
   ]
  },
  {
   "title": "Quorum Majority",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(swarm_manager_nodes{instance=~\"$v_nodes\", state=\"ready\"} > 0)",
     "legendFormat": "__auto"
    },
    { "expression": "floor(($A / 2 ) + 1)", "type": "math" }
   ]
  },
  {
   "title": "Available Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_nodes{instance=\"$leader\", state=\"ready\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Running Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_services_total{instance=\"$leader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(swarm_manager_tasks_total{instance=\"$leader\", state=\"running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total config objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_configs_total{instance=\"$leader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total secret objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_secrets_total{instance=\"$leader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Containers CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$v_nodes\", name=~\".+\"}[$__interval])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Containers RAM Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{instance=~\"$v_nodes\", name=~\".+\"}[$__interval])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Containers Received Network Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$v_nodes\", name=~\".+\"}[$__interval])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Containers Sent Network Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$v_nodes\", name=~\".+\"}[$__interval])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Usages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$node\", name=~\".+\"}[5m])) by (name) *100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$node\", name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{instance=~\"$node\", name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$node\", name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$node\", name=~\".+\"}[5m])) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}